/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package owasp.gradle.plugin.deprecation.sample;

public class Application {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
}
