/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package owasp.gradle.plugin.deprecation.sample;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
